// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMm0cV4jVXLGGKHkekpowDqVNWu-JzFlw',
    appId: '1:49998586822:web:a6cae04c3f94f00e6088c7',
    messagingSenderId: '49998586822',
    projectId: 'architecture-16213',
    authDomain: 'architecture-16213.firebaseapp.com',
    storageBucket: 'architecture-16213.appspot.com',
    measurementId: 'G-DRC2XSL104',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsfFDiLU5pHveCIy-duP1pZehuxuIE5Ik',
    appId: '1:49998586822:android:36f181b576e1c17a6088c7',
    messagingSenderId: '49998586822',
    projectId: 'architecture-16213',
    storageBucket: 'architecture-16213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Qt2nuw039CLo54oDRF_485_oCmC8_V0',
    appId: '1:49998586822:ios:e5197678cafbcd616088c7',
    messagingSenderId: '49998586822',
    projectId: 'architecture-16213',
    storageBucket: 'architecture-16213.appspot.com',
    iosBundleId: 'com.example.architecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Qt2nuw039CLo54oDRF_485_oCmC8_V0',
    appId: '1:49998586822:ios:e5197678cafbcd616088c7',
    messagingSenderId: '49998586822',
    projectId: 'architecture-16213',
    storageBucket: 'architecture-16213.appspot.com',
    iosBundleId: 'com.example.architecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMm0cV4jVXLGGKHkekpowDqVNWu-JzFlw',
    appId: '1:49998586822:web:b5c5fafd0ebc2ed26088c7',
    messagingSenderId: '49998586822',
    projectId: 'architecture-16213',
    authDomain: 'architecture-16213.firebaseapp.com',
    storageBucket: 'architecture-16213.appspot.com',
    measurementId: 'G-2D9FS3N5SD',
  );
}
